package detect

import (
	"testing"

	"github.com/CaliLuke/lagotto/internal/audit"
)

func layerPolicyFixture(handler string) map[string]string {
	return map[string]string{
		"service/users/users.go": `package users
type Store struct{}
func (*Store) Load() string { return "user" }
`,
		"service/billing/billing.go": `package billing
type Store struct{}
func (*Store) Load() string { return "bill" }
`,
		"gen/api/api.go": `// Code generated by fixture. DO NOT EDIT.
package api
type Response struct { Value string }
`,
		"transport/handler.go": handler,
	}
}

func testLayerPolicyRule() LayerPolicyRule {
	return LayerPolicyRule{
		Name:                       "thin-transport",
		Paths:                      []string{"transport/**"},
		Dependencies:               []string{"service/**"},
		GeneratedTypes:             []string{"gen/**"},
		MaxCoordinatedDependencies: 1,
		Severity:                   audit.SevMedium,
	}
}

func TestG14_MultipleDependenciesAndGeneratedMappingFire(t *testing.T) {
	handler := `package transport
import (
	"example.com/test/gen/api"
	"example.com/test/service/billing"
	"example.com/test/service/users"
)
type Handler struct { Users *users.Store; Billing *billing.Store }
func (h *Handler) Handle() *api.Response {
	user := h.Users.Load()
	bill := h.Billing.Load()
	return &api.Response{Value: user + bill}
}
`
	findings := ScanLayerPolicy(fakeModule(t, layerPolicyFixture(handler)), []LayerPolicyRule{testLayerPolicyRule()})
	if len(findings) != 1 || findings[0].SmellID != "G14" || findings[0].Severity != audit.SevMedium {
		t.Fatalf("expected one MEDIUM G14, got %+v", findings)
	}
	if findings[0].Location != "transport/handler.go:Handler.Handle" || findings[0].Evidence["dependency_type_count"] != 2 {
		t.Fatalf("unexpected G14 location/evidence: %+v", findings[0])
	}
	calls, ok := findings[0].Evidence["dependency_calls"].([]layerDependencyCall)
	if !ok || len(calls) != 2 || calls[0].Type == calls[1].Type {
		t.Fatalf("expected actionable typed dependency calls, got %#v", findings[0].Evidence)
	}
	mappings, ok := findings[0].Evidence["generated_mappings"].([]layerGeneratedMapping)
	if !ok || len(mappings) != 1 || mappings[0].Kind != "composite_literal" {
		t.Fatalf("expected generated composite mapping evidence, got %#v", findings[0].Evidence)
	}
}

func TestG14_RequiresBothCoordinationAndMapping(t *testing.T) {
	withoutMapping := `package transport
import (
	"example.com/test/service/billing"
	"example.com/test/service/users"
)
type Handler struct { Users *users.Store; Billing *billing.Store }
func (h *Handler) Handle() string { return h.Users.Load() + h.Billing.Load() }
`
	if findings := ScanLayerPolicy(fakeModule(t, layerPolicyFixture(withoutMapping)), []LayerPolicyRule{testLayerPolicyRule()}); containsID(findings, "G14") {
		t.Fatalf("did not expect coordination alone to fire, got %+v", findings)
	}

	oneDependency := `package transport
import (
	"example.com/test/gen/api"
	"example.com/test/service/users"
)
type Handler struct { Users *users.Store }
func (h *Handler) Handle() *api.Response {
	return &api.Response{Value: h.Users.Load() + h.Users.Load()}
}
`
	if findings := ScanLayerPolicy(fakeModule(t, layerPolicyFixture(oneDependency)), []LayerPolicyRule{testLayerPolicyRule()}); containsID(findings, "G14") {
		t.Fatalf("repeated calls to one dependency type should not fire, got %+v", findings)
	}
}

func TestG14_LocalMapperResultCountsAsGeneratedMapping(t *testing.T) {
	handler := `package transport
import (
	"example.com/test/gen/api"
	"example.com/test/service/billing"
	"example.com/test/service/users"
)
type Handler struct { Users *users.Store; Billing *billing.Store }
func mapResponse(value string) *api.Response { return &api.Response{Value: value} }
func (h *Handler) Handle() *api.Response {
	return mapResponse(h.Users.Load() + h.Billing.Load())
}
`
	findings := ScanLayerPolicy(fakeModule(t, layerPolicyFixture(handler)), []LayerPolicyRule{testLayerPolicyRule()})
	if len(findings) != 1 {
		t.Fatalf("expected local generated-result mapper to qualify G14, got %+v", findings)
	}
	mappings := findings[0].Evidence["generated_mappings"].([]layerGeneratedMapping)
	if len(mappings) != 1 || mappings[0].Kind != "generated_result" {
		t.Fatalf("expected generated-result evidence, got %+v", mappings)
	}
}

func TestG14_PackageConstructorDoesNotCreateASecondDependency(t *testing.T) {
	files := layerPolicyFixture(`package transport
import (
	"example.com/test/gen/api"
	"example.com/test/service/users"
)
type Handler struct{}
func (h *Handler) Handle() *api.Response {
	store := users.NewStore()
	return &api.Response{Value: store.Load()}
}
`)
	files["service/users/users.go"] = `package users
type Store struct{}
func NewStore() *Store { return &Store{} }
func (*Store) Load() string { return "user" }
`
	findings := ScanLayerPolicy(fakeModule(t, files), []LayerPolicyRule{testLayerPolicyRule()})
	if containsID(findings, "G14") {
		t.Fatalf("constructor plus one service is wiring, not two coordinated dependencies: %+v", findings)
	}
}

func TestG14_PackageHelperAndReceiverInSamePackageAreOneDependency(t *testing.T) {
	files := layerPolicyFixture(`package transport
import (
	"example.com/test/gen/api"
	"example.com/test/service/users"
)
type Handler struct { Users *users.Store }
func (h *Handler) Handle() *api.Response {
	return &api.Response{Value: users.DefaultName() + h.Users.Load()}
}
`)
	files["service/users/users.go"] = `package users
type Store struct{}
func DefaultName() string { return "default" }
func (*Store) Load() string { return "user" }
`
	findings := ScanLayerPolicy(fakeModule(t, files), []LayerPolicyRule{testLayerPolicyRule()})
	if containsID(findings, "G14") {
		t.Fatalf("a same-package helper and receiver belong to one dependency: %+v", findings)
	}
}

func TestG14_FieldAssignmentAndTypeConversionAreMappingEvidence(t *testing.T) {
	files := layerPolicyFixture(`package transport
import (
	"example.com/test/gen/api"
	"example.com/test/service/billing"
	"example.com/test/service/users"
)
type Handler struct { Users *users.Store; Billing *billing.Store }
func (h *Handler) Handle() *api.Response {
	response := &api.Response{}
	response.Status = api.Status(h.Users.Load() + h.Billing.Load())
	return response
}
`)
	files["gen/api/api.go"] = `// Code generated by fixture. DO NOT EDIT.
package api
type Status string
type Response struct { Status Status }
`
	findings := ScanLayerPolicy(fakeModule(t, files), []LayerPolicyRule{testLayerPolicyRule()})
	if len(findings) != 1 {
		t.Fatalf("expected field assignment and conversion to qualify mapping, got %+v", findings)
	}
	kinds := map[string]bool{}
	for _, mapping := range findings[0].Evidence["generated_mappings"].([]layerGeneratedMapping) {
		kinds[mapping.Kind] = true
	}
	for _, kind := range []string{"composite_literal", "field_assignment", "type_conversion"} {
		if !kinds[kind] {
			t.Fatalf("expected %s mapping evidence, got %+v", kind, kinds)
		}
	}
}

func TestG14_NestedClosureCallsAreNotAttributedToOuterFunction(t *testing.T) {
	handler := `package transport
import (
	"example.com/test/gen/api"
	"example.com/test/service/billing"
	"example.com/test/service/users"
)
type Handler struct { Users *users.Store; Billing *billing.Store }
func (h *Handler) Handle() *api.Response {
	work := func() string { return h.Users.Load() + h.Billing.Load() }
	_ = work
	return &api.Response{Value: "deferred"}
}
`
	findings := ScanLayerPolicy(fakeModule(t, layerPolicyFixture(handler)), []LayerPolicyRule{testLayerPolicyRule()})
	if containsID(findings, "G14") {
		t.Fatalf("nested closure dependencies should not be attributed to outer function: %+v", findings)
	}
}

func TestPolicyConstructorRequiresConstructorShape(t *testing.T) {
	files := layerPolicyFixture(`package transport
import (
	"example.com/test/gen/api"
	"example.com/test/service/billing"
	"example.com/test/service/users"
)
type Handler struct { Users *users.Store }
func (h *Handler) Handle() *api.Response {
	return &api.Response{Value: h.Users.Load() + billing.NewerValue()}
}
`)
	files["service/users/users.go"] = `package users
type Store struct{}
func (*Store) Load() string { return "user" }
`
	files["service/billing/billing.go"] = `package billing
func NewerValue() string { return "newer" }
`
	findings := ScanLayerPolicy(fakeModule(t, files), []LayerPolicyRule{testLayerPolicyRule()})
	if len(findings) != 1 || findings[0].Evidence["dependency_type_count"] != 2 {
		t.Fatalf("non-constructor New-prefixed operation should remain visible, got %+v", findings)
	}
}

func TestG14_ThresholdScopeAndNoRules(t *testing.T) {
	handler := `package transport
import (
	"example.com/test/gen/api"
	"example.com/test/service/billing"
	"example.com/test/service/users"
)
type Handler struct { Users *users.Store; Billing *billing.Store }
func (h *Handler) Handle() *api.Response {
	return &api.Response{Value: h.Users.Load() + h.Billing.Load()}
}
`
	packages := fakeModule(t, layerPolicyFixture(handler))
	if findings := ScanLayerPolicy(packages, nil); len(findings) != 0 {
		t.Fatalf("G14 must be opt-in, got %+v", findings)
	}
	rule := testLayerPolicyRule()
	rule.MaxCoordinatedDependencies = 2
	if findings := ScanLayerPolicy(packages, []LayerPolicyRule{rule}); containsID(findings, "G14") {
		t.Fatalf("configured threshold should allow two dependencies, got %+v", findings)
	}
	rule = testLayerPolicyRule()
	rule.Paths = []string{"delivery/**"}
	if findings := ScanLayerPolicy(packages, []LayerPolicyRule{rule}); containsID(findings, "G14") {
		t.Fatalf("out-of-scope package should not fire, got %+v", findings)
	}
}

func TestValidateLayerPolicyRules(t *testing.T) {
	valid := testLayerPolicyRule()
	if err := ValidateLayerPolicyRules([]LayerPolicyRule{valid}); err != nil {
		t.Fatal(err)
	}
	for name, mutate := range map[string]func(*LayerPolicyRule){
		"name":         func(rule *LayerPolicyRule) { rule.Name = "" },
		"paths":        func(rule *LayerPolicyRule) { rule.Paths = nil },
		"dependencies": func(rule *LayerPolicyRule) { rule.Dependencies = nil },
		"generated":    func(rule *LayerPolicyRule) { rule.GeneratedTypes = nil },
		"threshold":    func(rule *LayerPolicyRule) { rule.MaxCoordinatedDependencies = -1 },
		"severity":     func(rule *LayerPolicyRule) { rule.Severity = "UNKNOWN" },
	} {
		t.Run(name, func(t *testing.T) {
			rule := valid
			mutate(&rule)
			if err := ValidateLayerPolicyRules([]LayerPolicyRule{rule}); err == nil {
				t.Fatal("expected validation error")
			}
		})
	}
	if err := ValidateLayerPolicyRules([]LayerPolicyRule{valid, valid}); err == nil {
		t.Fatal("expected duplicate rule validation error")
	}
}

func TestPolicyPatternMatching(t *testing.T) {
	for _, test := range []struct {
		pattern, value, module string
	}{
		{"internal/transport/**", "github.com/acme/app/internal/transport", "github.com/acme/app"},
		{"internal/transport/**", "github.com/acme/app/internal/transport/http/handler.go", "github.com/acme/app"},
		{"github.com/acme/shared/*", "github.com/acme/shared/store", "github.com/acme/app"},
	} {
		if !matchesPolicyPatterns([]string{test.pattern}, test.value, test.module) {
			t.Fatalf("pattern %q should match %q", test.pattern, test.value)
		}
	}
	if matchesPolicyPatterns([]string{"internal/transport/**"}, "github.com/acme/app/internal/service", "github.com/acme/app") {
		t.Fatal("transport pattern should not match service package")
	}
}
