package detect

import "testing"

// TestG2_StutterNames fires when a package has exported identifiers
// that repeat the package name — the canonical `lanes.LaneConfig`
// shape that should be `lanes.Config` per Go style.
func TestG2_StutterNames(t *testing.T) {
	pkgs := fakeModule(t, map[string]string{"lanes/lanes.go": `package lanes

type LaneConfig struct{}
type LaneState int
func LaneNew() *LaneConfig { return nil }
`,
		"go.mod": "module example.com/test\ngo 1.21\n",
	})
	findings := ScanStutter(pkgs)
	if !containsID(findings, "G2") {
		t.Fatalf("expected G2, got %v", findingIDs(findings))
	}
}

// TestG2_NonStutter_NoFire ensures clean naming does not trigger.
func TestG2_NonStutter_NoFire(t *testing.T) {
	pkgs := fakeModule(t, map[string]string{"lanes/lanes.go": `package lanes

type Config struct{}
type State int
func New() *Config { return nil }
`,
		"go.mod": "module example.com/test\ngo 1.21\n",
	})
	findings := ScanStutter(pkgs)
	if containsID(findings, "G2") {
		t.Fatalf("did not expect G2 for clean names, got %+v", findings)
	}
}

func TestG2_ShortPluralAndUnicodeNames(t *testing.T) {
	if stutters("s", "Service") {
		t.Fatal("one-letter s package must not underflow into an empty prefix")
	}
	if !stutters("écho", "ÉchoConfig") {
		t.Fatal("expected a Unicode identifier boundary to be detected")
	}
}

func TestG2_GeneratedFile_NoFire(t *testing.T) {
	pkgs := fakeModule(t, map[string]string{"lanes/lanes.go": `// Code generated by names. DO NOT EDIT.
package lanes

type LaneConfig struct{}
`})
	if findings := ScanStutter(pkgs); containsID(findings, "G2") {
		t.Fatalf("did not expect G2 for generated declarations, got %+v", findings)
	}
}
