package detect

import (
	"strings"
	"testing"
)

// TestG8_ReExportTunnel fires when a package's only role is to
// re-export names from a deeper package — a TypeScript "barrel"
// pattern that adds an indirection layer with no Go-side benefit.
func TestG8_ReExportTunnel(t *testing.T) {
	pkgs := fakeModule(t, map[string]string{
		"go.mod":         "module example.com/test\ngo 1.21\n",
		"inner/inner.go": "package inner\n\ntype Foo struct{ N int }\n\nvar Default = Foo{N: 1}\n\nfunc Hello() string { return \"hi\" }\n",
		"outer/outer.go": "package outer\n\nimport \"example.com/test/inner\"\n\ntype Foo = inner.Foo\n\nvar Default = inner.Default\n\nfunc Hello() string { return inner.Hello() }\n",
	})
	findings := ScanReExportTunnel(pkgs)
	if !containsID(findings, "G8") {
		t.Fatalf("expected G8, got %v", findingIDs(findings))
	}
	if !strings.Contains(findings[0].Location, "outer") {
		t.Errorf("expected outer package in location, got %s", findings[0].Location)
	}
}

func TestG8_FunctionReExportTunnel(t *testing.T) {
	pkgs := fakeModule(t, map[string]string{
		"go.mod":         "module example.com/test\ngo 1.21\n",
		"inner/inner.go": "package inner\n\nfunc Hello(name string) string { return name }\n\nfunc Goodbye(name string) string { return name }\n\nfunc Ping() string { return \"pong\" }\n",
		"outer/outer.go": "package outer\n\nimport \"example.com/test/inner\"\n\nfunc Hello(name string) string { return inner.Hello(name) }\n\nfunc Goodbye(name string) string { return inner.Goodbye(name) }\n\nfunc Ping() string { return inner.Ping() }\n",
	})
	findings := ScanReExportTunnel(pkgs)
	if !containsID(findings, "G8") {
		t.Fatalf("expected G8, got %v", findingIDs(findings))
	}
}

func TestG8_GeneratedFactories_NoFire(t *testing.T) {
	pkgs := fakeModule(t, map[string]string{
		"go.mod": "module example.com/test\ngo 1.21\n",
		"runtime/runtime.go": `package runtime

type ServiceError struct {
	Err  error
	Code string
}

func NewServiceError(err error, code string) *ServiceError {
	return &ServiceError{Err: err, Code: code}
}
`,
		"orders/errors.go": `// Code generated by ExampleGen, DO NOT EDIT.
package orders

import runtime "example.com/test/runtime"

func MakeInvalidRequest(err error) *runtime.ServiceError {
	return runtime.NewServiceError(err, "invalid_request")
}

func MakeUnauthorized(err error) *runtime.ServiceError {
	return runtime.NewServiceError(err, "unauthorized")
}

func MakeConflict(err error) *runtime.ServiceError {
	return runtime.NewServiceError(err, "conflict")
}
`,
	})
	findings := ScanReExportTunnel(pkgs)
	if containsID(findings, "G8") {
		t.Fatalf("did not expect G8 for generated service factories, got %+v", findings)
	}
}

// TestG8_RealPackage_NoFire ensures a package with its own logic
// (here a method on a local type) does not fire even if it also
// re-exports symbols.
func TestG8_RealPackage_NoFire(t *testing.T) {
	pkgs := fakeModule(t, map[string]string{
		"a.go": "package foo\n\ntype Bar struct{ N int }\n\nfunc (b Bar) Add(n int) int { return b.N + n }\n\nvar Sentinel = Bar{N: 42}\n",
	})
	findings := ScanReExportTunnel(pkgs)
	if containsID(findings, "G8") {
		t.Fatalf("did not expect G8 for self-contained package, got %+v", findings)
	}
}
